### ISSUE TITLE
Implement one filter

### ISSUE THREAD

**Issue by Teddarific** [Left-on-Read/app#6]
Implement filtering - we can start with just a single filter, such as by date.

~This should be redux-driven.~

**Comment by alexdanilowicz** [comment]
I'm making an executive decision to use Context instead of Redux here. The Electron Boilerplate v2.0 is even moving off of redux. See https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/2233 and https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/2367 and https://github.com/electron-react-boilerplate/electron-react-boilerplate/pull/2661

**Comment by alexdanilowicz** [comment]
Above commit message referenced wrong issue #. It meant to resolve #7. Re-opening this.
