### ISSUE TITLE
Join contacts to all core tables

### ISSUE THREAD

**Issue by Teddarific** [Left-on-Read/app#7]
If there is a .vcf file on the user's computer, it should parse the contacts and join them to the core tables.

**Comment by alexdanilowicz** [comment]
Instead of having the user export a .vcf, we are likely going to go with reading their populated `*.abcddb` file instead.

**Comment by alexdanilowicz** [comment]
Going to work on this next, starting tomorrow.

**Comment by alexdanilowicz** [comment]
Pasting this here because I have nowhere else to put it. 

Implementation flow:

First: 
- 1) copy the AddressBook.db file to the .leftonread folder 
- 2) loop over all possible the AddressBook.db files and find the one that is populated
- 3) if none are populated, then skip the ALTER/UPDATE step (5), but (7) will be the same
- 4) with the populated one, open it and `ATTACH` it to existing chat.db database connection 
- If successfully attached, you should be able to do the following:

```
- 5)
ALTER TABLE handle ADD contact_name VARCHAR(255);

UPDATE handle 
SET contact_name = (SELECT address_book_table.name FROM address_book_table WHERE handle.id = address_book_table.phone);

# 6) Close the Contacts DB connection now

-- 7)
-- downstream usage in core table
SELECT coalesce(contact_name, handle.id) as contact FROM handle
```

The whole idea is to alter the existing chat.db handle table directly by adding a `contact_person` column to it directly.

PROS:
- We worry about this one on initialize and then never again
- We don't have to worry about JOINs down the road
- We simply reference the handle table every time and use a `coalesce`. You could probs get around the coalesce if I gave this more thought.
- We can close the addressbook.db file immediately
CONS:
- contacts isn't it's own table... which would make more sense logically?

**Comment by alexdanilowicz** [comment]
This coming along nicely. For posterity's sake, the query for this will be: 

```sql
CREATE TABLE CONTACTS_TABLE AS
WITH CONTACTS_CLEAN_TABLE AS (
SELECT 
	ZABCDRECORD.Z_PK, 
	ZABCDRECORD.ZFIRSTNAME,
	ZABCDRECORD.ZLASTNAME, 
	-- TODO: I understand this is ugly... use regex.
	replace(replace(replace(replace(replace(replace(ZABCDPHONENUMBER.ZFULLNUMBER, "(", ""), ")", ""), "_", ""), "-", ""), " ", ""), "+", "") as ZFULLNUMBER
FROM ZABCDRECORD
LEFT JOIN ZABCDPHONENUMBER ON ZABCDPHONENUMBER.ZOWNER = ZABCDRECORD.Z_PK
WHERE ZABCDPHONENUMBER.ZFULLNUMBER IS NOT NULL
)
--- NOTE: in the chat.db the format is +1619... in other words
--- chat.db lists the country code always. The addressbook.db, however, does not always include the country code.
--- Therefore, we remove the + and the country code, and FILTER on the 10-digit length.
--- All phone numbers in the US/Canada are 10-digit... this assumption may not work as well for users in other countries
SELECT 
ZFIRSTNAME || " " || ZLASTNAME  as contact_name,
CASE WHEN LENGTH(ZFULLNUMBER) > 10
	THEN SUBSTR(ZFULLNUMBER, -10, 10)
	ELSE ZFULLNUMBER
END AS contact_phone
FROM CONTACTS_CLEAN_TABLE
```
